import Foundation

/// Lowers the type-checked Swift AST of a .smetal file to Metal Shading Language.
struct Emitter {
    let ast: TypedAST
    var specializations: [String: String] = [:]

    private var structTypes: Set<String> = []

    private static let scalarTypes: [String: String] = [
        "Float": "float", "Double": "float", "Int": "int", "Int32": "int",
        "UInt": "uint", "UInt32": "uint", "Bool": "bool",
        "Half": "half", "Float16": "half",
        "Float2": "float2", "Float3": "float3", "Float4": "float4",
        "UInt2": "uint2", "UInt3": "uint3",
    ]

    /// Swift names that lower to an MSL function of the same or a different name.
    private static let intrinsics: [String: String] = [
        "min": "min", "max": "max", "abs": "abs", "sqrt": "sqrt",
        "sin": "sin", "cos": "cos", "pow": "pow", "clamp": "clamp",
        "floor": "floor", "ceil": "ceil", "mix": "mix", "dot": "dot",
    ]

    /// Initializers that lower to an MSL conversion or vector constructor.
    private static let conversions: [String: String] = [
        "Float": "float", "Int": "int", "UInt": "uint", "UInt32": "uint",
        "Int32": "int", "Half": "half",
        "Float2": "float2", "Float3": "float3", "Float4": "float4",
        "UInt2": "uint2", "UInt3": "uint3",
    ]

    /// Builtin index types and their entry-point attribute.
    private static let indexAttributes: [String: String] = [
        "GridIndex": "thread_position_in_grid",
        "VertexIndex": "vertex_id",
        "InstanceIndex": "instance_id",
    ]

    private static let memberAttributes: [String: String] = [
        "position": "position", "pointSize": "point_size", "flat": "flat",
    ]

    mutating func emit() throws -> String {
        var output = """
        // Generated by smetal from \((ast.path as NSString).lastPathComponent)
        // Do not edit — edit the .smetal source instead.
        #include <metal_stdlib>
        using namespace metal;


        """

        let declarations = ast.declarations.filter { !$0.isImplicit }

        for declaration in declarations where declaration.kind == "struct_decl" {
            if let name = declaration.name { structTypes.insert(name) }
        }

        // A top-level `let` shows up as a pattern_binding_decl carrying the
        // initializer plus a var_decl carrying the name; read the pair together.
        var index = 0
        while index < declarations.count {
            let declaration = declarations[index]
            switch declaration.kind {
            case "pattern_binding_decl":
                output += try emitGlobalConstant(declaration) + "\n"
            case "var_decl":
                break
            case "struct_decl":
                output += try emitStruct(declaration) + "\n"
            case "func_decl":
                output += try emitFunction(declaration) + "\n"
            case "import_decl", "top_level_code_decl":
                break
            default:
                throw SMetalError("unsupported top-level declaration: \(declaration.kind)")
            }
            index += 1
        }
        return output
    }

    // MARK: - Declarations

    private func emitGlobalConstant(_ node: ASTNode) throws -> String {
        guard let entry = node.firstChild(of: "pattern_entry"),
              let named = entry.firstDescendant(of: "pattern_named"),
              let name = named.name else {
            throw SMetalError("malformed global declaration")
        }
        let type = try metalType(named.type, context: "global '\(name)'")

        let value: String
        if let override = specializations[name] {
            value = override
        } else if let initializer = entry.children.first(where: { $0["label"] == "processed_init" }) {
            value = try emitExpression(initializer)
        } else {
            throw SMetalError("global '\(name)' needs an initial value")
        }
        let note = specializations[name].map { _ in "  // specialized" } ?? ""
        return "constant \(type) \(name) = \(value);\(note)\n"
    }

    private func emitStruct(_ node: ASTNode) throws -> String {
        guard let name = node.name else { throw SMetalError("unnamed struct") }

        var members: [String] = []
        var colorIndex = 0
        // Property wrappers synthesize accessors and a backing `_name` var; only
        // the explicit var_decls describe the shader's actual layout.
        for member in node.children(of: "var_decl") where !member.isImplicit {
            guard let memberName = member.name else { continue }
            let type = try metalType(member.type, context: "'\(name).\(memberName)'")

            var attribute = ""
            if let wrapper = member.firstChild(of: "custom_attr")?["type"] {
                if wrapper == "color" {
                    attribute = " [[color(\(colorIndex))]]"
                    colorIndex += 1
                } else if let mapped = Self.memberAttributes[wrapper] {
                    attribute = " [[\(mapped)]]"
                } else {
                    throw SMetalError("unknown attribute '@\(wrapper)' on \(name).\(memberName)")
                }
            }
            members.append("    \(type) \(memberName)\(attribute);")
        }

        guard !members.isEmpty else { throw SMetalError("struct '\(name)' has no stored properties") }
        return "struct \(name) {\n" + members.joined(separator: "\n") + "\n};\n"
    }

    private func emitFunction(_ node: ASTNode) throws -> String {
        guard let signature = node.name else { throw SMetalError("unnamed function") }
        let name = String(signature.split(separator: "(").first ?? "")

        let stage = node.firstChild(of: "custom_attr")?["type"]
        let qualifier: String
        switch stage {
        case "compute": qualifier = "kernel"
        case "vertex": qualifier = "vertex"
        case "fragment": qualifier = "fragment"
        case nil: qualifier = "static"
        case let other?: throw SMetalError("unknown attribute '@\(other)' on \(name)")
        }
        let isEntryPoint = qualifier != "static"

        var parameters: [String] = []
        var bufferIndex = 0
        for parameter in node.firstChild(of: "parameter_list")?.children(of: "parameter") ?? [] {
            parameters.append(try emitParameter(parameter, bufferIndex: &bufferIndex, isEntryPoint: isEntryPoint))
        }

        guard let body = node.firstChild(of: "brace_stmt") else {
            throw SMetalError("function '\(name)' has no body")
        }
        let returnType = try metalReturnType(node["result"], context: "'\(name)'")

        return """
        \(qualifier) \(returnType) \(name)(
            \(parameters.joined(separator: ",\n    "))
        ) \(try emitBlock(body, indent: 0))

        """
    }

    private func emitParameter(_ node: ASTNode, bufferIndex: inout Int, isEntryPoint: Bool) throws -> String {
        guard let name = node.name else { throw SMetalError("unnamed parameter") }
        guard let type = node.type else { throw SMetalError("parameter '\(name)' has no type") }

        if let attribute = Self.indexAttributes[type] {
            return isEntryPoint ? "uint \(name) [[\(attribute)]]" : "uint \(name)"
        }

        if let element = bufferElement(of: type) {
            let elementType = try metalType(element, context: "Buffer element")
            defer { bufferIndex += 1 }
            let binding = isEntryPoint ? " [[buffer(\(bufferIndex))]]" : ""
            return "device \(elementType) *\(name)\(binding)"
        }

        if structTypes.contains(type) {
            // A struct parameter on an entry point is rasterizer input.
            return isEntryPoint ? "\(type) \(name) [[stage_in]]" : "\(type) \(name)"
        }

        let mapped = try metalType(type, context: "parameter '\(name)'")
        if isEntryPoint {
            defer { bufferIndex += 1 }
            return "constant \(mapped) &\(name) [[buffer(\(bufferIndex))]]"
        }
        return "\(mapped) \(name)"
    }

    // MARK: - Statements

    private func emitBlock(_ node: ASTNode, indent: Int) throws -> String {
        let pad = String(repeating: "    ", count: indent + 1)
        var lines: [String] = []
        for statement in node.children {
            guard let text = try emitStatement(statement, indent: indent + 1) else { continue }
            lines.append(pad + text)
        }
        return "{\n" + lines.joined(separator: "\n") + "\n" + String(repeating: "    ", count: indent) + "}"
    }

    /// Returns nil for nodes that carry no runtime effect, such as the var_decl
    /// that accompanies a local pattern_binding_decl.
    private func emitStatement(_ node: ASTNode, indent: Int) throws -> String? {
        switch node.kind {
        case "pattern_binding_decl":
            guard let entry = node.firstChild(of: "pattern_entry"),
                  let named = entry.firstDescendant(of: "pattern_named"),
                  let name = named.name else {
                throw SMetalError("malformed local declaration")
            }
            let type = try metalType(named.type, context: "local '\(name)'")
            guard let initializer = entry.children.first(where: { $0["label"] == "processed_init" }) else {
                return "\(type) \(name);"
            }
            return "\(type) \(name) = \(try emitExpression(initializer));"

        case "var_decl", "pattern_entry":
            return nil

        case "assign_expr":
            guard node.children.count == 2 else { throw SMetalError("malformed assignment") }
            return "\(try emitExpression(node.children[0])) = \(try emitExpression(node.children[1]));"

        case "return_stmt":
            guard let value = node.children.first else { return "return;" }
            return "return \(try emitExpression(value));"

        case "if_stmt":
            let parts = node.children
            guard parts.count >= 2 else { throw SMetalError("malformed if") }
            var text = "if (\(try emitExpression(parts[0]))) \(try emitBlock(parts[1], indent: indent))"
            if parts.count >= 3 {
                let alternative = parts[2]
                text += alternative.kind == "brace_stmt"
                    ? " else \(try emitBlock(alternative, indent: indent))"
                    : " else \(try emitStatement(alternative, indent: indent) ?? ";")"
            }
            return text

        case "while_stmt":
            let parts = node.children
            guard parts.count == 2 else { throw SMetalError("malformed while") }
            return "while (\(try emitExpression(parts[0]))) \(try emitBlock(parts[1], indent: indent))"

        case "brace_stmt":
            return try emitBlock(node, indent: indent)

        default:
            return "\(try emitExpression(node));"
        }
    }

    // MARK: - Expressions

    private func emitExpression(_ node: ASTNode) throws -> String {
        switch node.kind {
        case "integer_literal_expr":
            guard let value = node["value"] else { throw SMetalError("integer literal without value") }
            return value

        case "float_literal_expr":
            guard let value = node["value"] else { throw SMetalError("float literal without value") }
            return value

        case "boolean_literal_expr":
            return node["value"] ?? "false"

        case "declref_expr":
            guard let name = node.declBaseName else { throw SMetalError("unresolved reference") }
            return name

        case "member_ref_expr":
            guard let base = node.children.first else { throw SMetalError("malformed member access") }
            guard let member = node.declBaseName else { throw SMetalError("unresolved member") }
            return "\(try emitExpression(base)).\(member)"

        case "subscript_expr":
            guard let base = node.children.first,
                  let arguments = node.firstChild(of: "argument_list"),
                  let index = arguments.children(of: "argument").first?.children.first else {
                throw SMetalError("malformed subscript")
            }
            return "\(try emitExpression(base))[\(try emitExpression(index))]"

        case "binary_expr":
            return try emitBinary(node)

        case "prefix_unary_expr":
            guard let callee = node.firstDescendant(of: "declref_expr"),
                  let operatorName = callee.declBaseName,
                  let operand = node.firstChild(of: "argument_list")?
                      .children(of: "argument").first?.children.first else {
                throw SMetalError("malformed unary expression")
            }
            return "\(operatorName)\(try emitExpression(operand))"

        case "paren_expr":
            guard let inner = node.children.first else { return "()" }
            return "(\(try emitExpression(inner)))"

        case "if_expr":
            let parts = node.children
            guard parts.count == 3 else { throw SMetalError("malformed ternary") }
            return "(\(try emitExpression(parts[0])) ? \(try emitExpression(parts[1])) : \(try emitExpression(parts[2])))"

        case "call_expr":
            return try emitCall(node)

        // swiftc inserts these around values; they have no MSL spelling.
        case "load_expr", "inout_expr", "paren_expr_implicit", "coerce_expr",
             "dot_syntax_call_expr", "await_expr", "abi_safe_conversion_expr":
            guard let inner = node.children.first else {
                throw SMetalError("empty \(node.kind)")
            }
            return try emitExpression(inner)

        case "constructor_ref_call_expr", "type_expr":
            throw SMetalError("unsupported type reference in expression position")

        default:
            // A labelled child such as processed_init wraps the real expression.
            if node["label"] != nil, let inner = node.children.first {
                return try emitExpression(inner)
            }
            throw SMetalError("unsupported expression: \(node.kind)")
        }
    }

    /// `a * b` arrives as binary_expr(dot_syntax_call_expr(operator), argument_list).
    private func emitBinary(_ node: ASTNode) throws -> String {
        guard let callee = node.children.first,
              let reference = callee.firstDescendant(of: "declref_expr"),
              let operatorName = reference.declBaseName else {
            throw SMetalError("unresolved operator")
        }
        guard let arguments = node.firstChild(of: "argument_list") else {
            throw SMetalError("operator '\(operatorName)' has no arguments")
        }
        let operands = try arguments.children(of: "argument").compactMap(\.children.first).map { try emitExpression($0) }
        guard operands.count == 2 else {
            throw SMetalError("operator '\(operatorName)' expects two operands")
        }

        let mapped: String
        switch operatorName {
        case "&&": mapped = "&&"
        case "||": mapped = "||"
        case "+", "-", "*", "/", "%", "<", ">", "<=", ">=", "==", "!=",
             "&", "|", "^", "<<", ">>":
            mapped = operatorName
        default:
            throw SMetalError("unsupported operator '\(operatorName)'")
        }
        return "(\(operands[0]) \(mapped) \(operands[1]))"
    }

    private func emitCall(_ node: ASTNode) throws -> String {
        guard let callee = node.children.first else { throw SMetalError("malformed call") }
        guard let arguments = node.firstChild(of: "argument_list") else {
            throw SMetalError("call has no argument list")
        }
        let operands = try arguments.children(of: "argument").compactMap(\.children.first).map { try emitExpression($0) }

        // A struct initializer reaches us as constructor_ref_call_expr whose
        // type_expr names the type; everything else is a plain function.
        if callee.kind == "constructor_ref_call_expr" {
            guard let typeName = callee.firstDescendant(of: "type_expr")?["typerepr"] else {
                throw SMetalError("unresolved initializer")
            }
            if let mapped = Self.conversions[typeName] {
                return "\(mapped)(\(operands.joined(separator: ", ")))"
            }
            if structTypes.contains(typeName) {
                return "\(typeName) { \(operands.joined(separator: ", ")) }"
            }
            throw SMetalError("no Metal constructor for '\(typeName)'")
        }

        guard let reference = callee.firstDescendant(of: "declref_expr"),
              let name = reference.declBaseName else {
            throw SMetalError("unresolved call")
        }
        if let mapped = Self.intrinsics[name] {
            return "\(mapped)(\(operands.joined(separator: ", ")))"
        }
        if let mapped = Self.conversions[name] {
            return "\(mapped)(\(operands.joined(separator: ", ")))"
        }
        // Helper functions declared in the same file are callable directly.
        return "\(name)(\(operands.joined(separator: ", ")))"
    }

    // MARK: - Types

    /// `Buffer<Float4>` → `Float4`.
    private func bufferElement(of type: String) -> String? {
        guard type.hasPrefix("Buffer<"), type.hasSuffix(">") else { return nil }
        return String(type.dropFirst("Buffer<".count).dropLast())
    }

    private func metalReturnType(_ type: String?, context: String) throws -> String {
        guard let type, type != "()" else { return "void" }
        return try metalType(type, context: context)
    }

    private func metalType(_ type: String?, context: String) throws -> String {
        guard var type else { throw SMetalError("\(context) has no type") }

        // Lvalue-ness is a property of the expression, not of the declaration.
        if type.hasPrefix("@lvalue ") { type = String(type.dropFirst("@lvalue ".count)) }

        if structTypes.contains(type) { return type }
        if let element = bufferElement(of: type) {
            return "device \(try metalType(element, context: context)) *"
        }
        guard let mapped = Self.scalarTypes[type] else {
            throw SMetalError("no Metal type for '\(type)' in \(context)")
        }
        return mapped
    }
}
