import CMSF
import Foundation

/// Translates the typed Swift AST of a .smetal file into Metal Shading Language.
struct Emitter {
    let tree: SyntaxTree
    var specializations: [String: String] = [:]

    /// Struct types declared in the file; usable as parameter, return, and local types.
    private var structTypes: Set<String> = []

    private static let scalarTypes: [String: String] = [
        "Float": "float", "Double": "float", "Int": "int", "Int32": "int",
        "UInt": "uint", "UInt32": "uint", "Bool": "bool", "Half": "half",
        "Float2": "float2", "Float3": "float3", "Float4": "float4",
        "UInt2": "uint2", "UInt3": "uint3",
    ]

    private static let intrinsics: [String: String] = [
        "min": "min", "max": "max", "abs": "abs", "sqrt": "sqrt",
        "sin": "sin", "cos": "cos", "pow": "pow", "clamp": "clamp",
        "floor": "floor", "ceil": "ceil", "mix": "mix", "dot": "dot",
        "Float": "float", "Int": "int", "UInt": "uint",
    ]

    mutating func emit() throws -> String {
        var output = """
        // Generated by smetal from \((tree.path as NSString).lastPathComponent)
        // Do not edit — edit the .smetal source instead.
        #include <metal_stdlib>
        using namespace metal;


        """

        for declaration in tree.root.children where declaration.kind == AST_STRUCT_DECL {
            structTypes.insert(declaration.firstTokenText)
        }

        for declaration in tree.root.children {
            switch declaration.kind {
            case AST_VAR_DECL, AST_LET_DECL:
                output += try emitGlobalConstant(declaration) + "\n"
            case AST_STRUCT_DECL:
                output += try emitStruct(declaration) + "\n"
            case AST_FUNC_DECL:
                output += try emitFunction(declaration) + "\n"
            case AST_IMPORT_DECL:
                continue
            default:
                throw SMetalError("unsupported top-level declaration: \(declaration.kindName)")
            }
        }
        return output
    }

    // MARK: - Declarations

    /// Top-level `let`/`var` becomes a Metal `constant`, overridable with `-D name=value`.
    private func emitGlobalConstant(_ node: Node) throws -> String {
        let name = node.varName
        let type = try metalType(of: try requireTypeAnnotation(node, context: "global '\(name)'"))
        let value: String
        if let override = specializations[name] {
            value = override
        } else if let initializer = node.children.first(where: { !isTypeNode($0) }) {
            value = try emitExpression(initializer)
        } else {
            throw SMetalError("global '\(name)' needs an initial value")
        }
        let note = specializations[name].map { _ in "  // specialized" } ?? ""
        return "constant \(type) \(name) = \(value);\(note)\n"
    }

    /// `struct` becomes a Metal struct; `@position` etc. become member attributes.
    private func emitStruct(_ node: Node) throws -> String {
        let name = node.firstTokenText
        guard let body = node.firstChild(of: AST_BLOCK) else {
            throw SMetalError("struct '\(name)' has no body")
        }

        var members: [String] = []
        var colorIndex = 0
        for member in body.children {
            guard member.kind == AST_VAR_DECL || member.kind == AST_LET_DECL else {
                throw SMetalError("struct '\(name)' may only contain stored properties")
            }
            let memberName = member.varName
            let type = try metalType(of: try requireTypeAnnotation(member, context: "'\(name).\(memberName)'"))
            var attribute = ""
            switch member.children(of: AST_ATTRIBUTE).first?.text {
            case "position": attribute = " [[position]]"
            case "pointSize": attribute = " [[point_size]]"
            case "flat": attribute = " [[flat]]"
            case "color":
                attribute = " [[color(\(colorIndex))]]"
                colorIndex += 1
            case nil: break
            case let other?: throw SMetalError("unknown attribute '@\(other)' on \(name).\(memberName)")
            }
            members.append("    \(type) \(memberName)\(attribute);")
        }

        return "struct \(name) {\n" + members.joined(separator: "\n") + "\n};\n"
    }

    private func emitFunction(_ node: Node) throws -> String {
        let name = node.declName
        let attributes = node.children(of: AST_ATTRIBUTE).map(\.text)
        let qualifier: String
        switch attributes.first {
        case "compute": qualifier = "kernel"
        case "vertex": qualifier = "vertex"
        case "fragment": qualifier = "fragment"
        case nil: qualifier = "static"
        case let other?: throw SMetalError("unknown attribute '@\(other)' on \(name)")
        }

        var parameters: [String] = []
        var bufferIndex = 0
        for parameter in node.children(of: AST_PARAM) {
            parameters.append(try emitParameter(parameter, bufferIndex: &bufferIndex, isEntryPoint: qualifier != "static"))
        }

        guard let body = node.firstChild(of: AST_BLOCK) else {
            throw SMetalError("function '\(name)' has no body")
        }
        let returnType = try node.children.first(where: { isTypeNode($0) }).map { try metalType(of: $0) } ?? "void"

        return """
        \(qualifier) \(returnType) \(name)(
            \(parameters.joined(separator: ",\n    "))
        ) \(try emitBlock(body, indent: 0))

        """
    }

    private func emitParameter(_ node: Node, bufferIndex: inout Int, isEntryPoint: Bool) throws -> String {
        let name = node.firstTokenText
        guard let typeNode = node.children.first(where: { isTypeNode($0) }) else {
            throw SMetalError("parameter '\(name)' has no type")
        }

        if typeNode.kind == AST_TYPE_IDENT {
            switch typeNode.firstTokenText {
            case "GridIndex":
                return isEntryPoint ? "uint \(name) [[thread_position_in_grid]]" : "uint \(name)"
            case "VertexIndex":
                return isEntryPoint ? "uint \(name) [[vertex_id]]" : "uint \(name)"
            case "InstanceIndex":
                return isEntryPoint ? "uint \(name) [[instance_id]]" : "uint \(name)"
            case let structName where structTypes.contains(structName):
                // A struct parameter on an entry point is rasterizer input.
                return isEntryPoint ? "\(structName) \(name) [[stage_in]]" : "\(structName) \(name)"
            default:
                break
            }
        }

        if typeNode.kind == AST_TYPE_GENERIC, typeNode.firstTokenText == "Buffer" {
            guard let element = typeNode.children.first(where: { isTypeNode($0) }) else {
                throw SMetalError("Buffer needs an element type")
            }
            let elementType = try metalType(of: element)
            defer { bufferIndex += 1 }
            let binding = isEntryPoint ? " [[buffer(\(bufferIndex))]]" : ""
            return "device \(elementType) *\(name)\(binding)"
        }

        let type = try metalType(of: typeNode)
        if isEntryPoint {
            defer { bufferIndex += 1 }
            return "constant \(type) &\(name) [[buffer(\(bufferIndex))]]"
        }
        return "\(type) \(name)"
    }

    // MARK: - Statements

    private func emitBlock(_ node: Node, indent: Int) throws -> String {
        let pad = String(repeating: "    ", count: indent + 1)
        var lines: [String] = []
        for statement in node.children {
            lines.append(pad + (try emitStatement(statement, indent: indent + 1)))
        }
        return "{\n" + lines.joined(separator: "\n") + "\n" + String(repeating: "    ", count: indent) + "}"
    }

    private func emitStatement(_ node: Node, indent: Int) throws -> String {
        switch node.kind {
        case AST_VAR_DECL, AST_LET_DECL:
            let name = node.varName
            let type = try metalType(of: try requireTypeAnnotation(node, context: "local '\(name)'"))
            guard let initializer = node.children.first(where: { !isTypeNode($0) }) else {
                return "\(type) \(name);"
            }
            return "\(type) \(name) = \(try emitExpression(initializer));"

        case AST_EXPR_STMT:
            guard let inner = node.children.first else { return ";" }
            return try emitStatement(inner, indent: indent)

        case AST_ASSIGN_EXPR:
            let parts = node.children
            guard parts.count == 2 else { throw SMetalError("malformed assignment") }
            return "\(try emitExpression(parts[0])) \(node.operatorText) \(try emitExpression(parts[1]));"

        case AST_RETURN_STMT:
            guard let value = node.children.first else { return "return;" }
            return "return \(try emitExpression(value));"

        case AST_IF_STMT:
            let parts = node.children
            guard parts.count >= 2 else { throw SMetalError("malformed if") }
            var text = "if (\(try emitExpression(parts[0]))) \(try emitBlock(parts[1], indent: indent))"
            if parts.count >= 3 {
                let alternative = parts[2]
                text += alternative.kind == AST_BLOCK
                    ? " else \(try emitBlock(alternative, indent: indent))"
                    : " else \(try emitStatement(alternative, indent: indent))"
            }
            return text

        case AST_WHILE_STMT:
            let parts = node.children
            guard parts.count == 2 else { throw SMetalError("malformed while") }
            return "while (\(try emitExpression(parts[0]))) \(try emitBlock(parts[1], indent: indent))"

        case AST_BLOCK:
            return try emitBlock(node, indent: indent)

        default:
            return "\(try emitExpression(node));"
        }
    }

    // MARK: - Expressions

    private func emitExpression(_ node: Node) throws -> String {
        switch node.kind {
        case AST_INTEGER_LITERAL:
            return String(node.intValue)
        case AST_FLOAT_LITERAL:
            return String(node.floatValue)
        case AST_BOOL_LITERAL:
            return node.boolValue ? "true" : "false"
        case AST_IDENT_EXPR:
            return node.firstTokenText

        case AST_BINARY_EXPR:
            let parts = node.children
            guard parts.count == 2 else { throw SMetalError("malformed binary expression") }
            return "(\(try emitExpression(parts[0])) \(node.operatorText) \(try emitExpression(parts[1])))"

        case AST_UNARY_EXPR:
            guard let operand = node.children.first else { throw SMetalError("malformed unary expression") }
            return "\(node.firstTokenText)\(try emitExpression(operand))"

        case AST_PAREN_EXPR:
            guard let inner = node.children.first else { return "()" }
            return "(\(try emitExpression(inner)))"

        case AST_SUBSCRIPT_EXPR:
            let parts = node.children
            guard parts.count >= 2 else { throw SMetalError("malformed subscript") }
            return "\(try emitExpression(parts[0]))[\(try emitExpression(parts[1]))]"

        case AST_MEMBER_EXPR:
            guard let base = node.children.first else { throw SMetalError("malformed member access") }
            let member = node.firstTokenText
            return "\(try emitExpression(base)).\(member)"

        case AST_CALL_EXPR:
            let parts = node.children
            guard let callee = parts.first else { throw SMetalError("malformed call") }
            let name = callee.firstTokenText
            guard let mapped = Self.intrinsics[name] else {
                throw SMetalError("unknown function '\(name)' — smetal only supports Metal intrinsics")
            }
            let arguments = try parts.dropFirst().map { try emitExpression($0) }
            return "\(mapped)(\(arguments.joined(separator: ", ")))"

        case AST_TERNARY_EXPR:
            let parts = node.children
            guard parts.count == 3 else { throw SMetalError("malformed ternary") }
            return "(\(try emitExpression(parts[0])) ? \(try emitExpression(parts[1])) : \(try emitExpression(parts[2])))"

        default:
            throw SMetalError("unsupported expression: \(node.kindName) «\(node.text)»")
        }
    }

    // MARK: - Types

    private func isTypeNode(_ node: Node) -> Bool {
        switch node.kind {
        case AST_TYPE_IDENT, AST_TYPE_GENERIC, AST_TYPE_ARRAY, AST_TYPE_OPTIONAL, AST_TYPE_TUPLE:
            return true
        default:
            return false
        }
    }

    private func requireTypeAnnotation(_ node: Node, context: String) throws -> Node {
        guard let type = node.children.first(where: { isTypeNode($0) }) else {
            throw SMetalError("\(context) needs an explicit type annotation")
        }
        return type
    }

    private func metalType(of node: Node) throws -> String {
        switch node.kind {
        case AST_TYPE_IDENT:
            let name = node.firstTokenText
            if structTypes.contains(name) { return name }
            guard let mapped = Self.scalarTypes[name] else {
                throw SMetalError("no Metal type for '\(name)'")
            }
            return mapped
        case AST_TYPE_GENERIC where node.firstTokenText == "Buffer":
            guard let element = node.children.first(where: { isTypeNode($0) }) else {
                throw SMetalError("Buffer needs an element type")
            }
            return "device \(try metalType(of: element)) *"
        default:
            throw SMetalError("unsupported type: \(node.kindName) «\(node.text)»")
        }
    }
}
