import Foundation

/// Lowers the type-checked Swift AST of a .schmetal file to Metal Shading Language.
struct Emitter {
    let ast: TypedAST
    var specializations: [String: String] = [:]

    private var structTypes: [String: String] = [:]

    private var shaderDeclarations: ShaderDeclarations { ShaderDeclarations(ast: ast) }

    mutating func emit() throws -> String {
        try shaderDeclarations.validate()
        var output = """
        // Generated by schmetal from \((ast.path as NSString).lastPathComponent)
        // Do not edit — edit the .schmetal source instead.
        #include <metal_stdlib>
        using namespace metal;


        """

        let declarations = ast.declarations.filter { !$0.isImplicit }

        for (index, declaration) in ast.structures.enumerated() {
            guard let type = declaration["instance_type"] else { throw SchmetalError("unresolved struct identity") }
            var name = "schmetal_type_\(index)"
            while ast.identifiers.contains(name) { name += "_" }
            structTypes[type] = name
        }
        for declaration in ast.structures { output += try emitStruct(declaration) + "\n" }

        // A top-level `let` shows up as a pattern_binding_decl carrying the
        // initializer plus a var_decl carrying the name; read the pair together.
        var index = 0
        while index < declarations.count {
            let declaration = declarations[index]
            switch declaration.kind {
            case "pattern_binding_decl":
                output += try emitGlobalConstant(declaration) + "\n"
            case "var_decl":
                break
            case "struct_decl", "typealias", "func_decl":
                break
            default:
                throw SchmetalError("unsupported top-level declaration: \(declaration.kind)")
            }
            index += 1
        }
        let functions = declarations.filter { $0.kind == "func_decl" }
        for function in functions where function.firstChild(of: "custom_attr") == nil {
            output += try emitFunction(function, prototype: true) + "\n"
        }
        for function in functions {
            output += try emitFunction(function, prototype: false) + "\n"
        }
        return output
    }

    // MARK: - Declarations

    private func emitGlobalConstant(_ node: ASTNode) throws -> String {
        guard let entry = node.firstChild(of: "pattern_entry"),
              let named = entry.firstDescendant(of: "pattern_named"),
              let name = named.name else {
            throw SchmetalError("malformed global declaration")
        }
        let type = try metalType(named.type, context: "global '\(name)'")

        let value: String
        if let override = specializations[name] {
            value = override
        } else if let initializer = entry.children.first(where: { $0["label"] == "processed_init" }) {
            value = try emitExpression(initializer)
        } else {
            throw SchmetalError("global '\(name)' needs an initial value")
        }
        let note = specializations[name].map { _ in "  // specialized" } ?? ""
        return "constant \(type) \(name) = \(value);\(note)\n"
    }

    private func emitStruct(_ node: ASTNode) throws -> String {
        guard let identity = node["instance_type"], let name = structTypes[identity] else { throw SchmetalError("unresolved struct") }

        var members: [String] = []
        var colorIndex = 0
        // Property wrappers synthesize accessors and a backing `_name` var; only
        // the explicit var_decls describe the shader's actual layout.
        for member in node.children(of: "var_decl") where !member.isImplicit {
            guard let memberName = member.name else { continue }
            let type = try metalType(member.type, context: "'\(name).\(memberName)'")

            var attribute = ""
            if let wrapper = member.firstChild(of: "custom_attr")?["type"] {
                if wrapper == ShaderLanguage.colorAttribute {
                    attribute = " [[color(\(colorIndex))]]"
                    colorIndex += 1
                } else if let mapped = ShaderLanguage.memberAttributes[wrapper] {
                    attribute = " [[\(mapped)]]"
                } else {
                    throw SchmetalError("unknown attribute '@\(wrapper)' on \(name).\(memberName)")
                }
            }
            members.append("    \(type) \(memberName)\(attribute);")
        }

        return "struct \(name) {\n" + members.joined(separator: "\n") + "\n};\n"
    }

    private func emitFunction(_ node: ASTNode, prototype: Bool) throws -> String {
        let name = try shaderDeclarations.functionName(node)

        let stage = node.firstChild(of: "custom_attr")?["type"]
        let qualifier: String
        switch stage {
        case nil: qualifier = "static"
        case let marker?:
            guard let mapped = ShaderLanguage.stages[marker] else {
                throw SchmetalError("unknown attribute '@\(marker)' on \(name)")
            }
            qualifier = mapped
        }
        let isEntryPoint = qualifier != "static"

        let parameterNodes = node.firstChild(of: "parameter_list")?.children(of: "parameter") ?? []
        let nonBindable = Set(parameterNodes.filter { ShaderLanguage.indexTypes[$0.type ?? ""] != nil }.compactMap(\.name))
        let automaticResources = Set(parameterNodes.filter {
            !nonBindable.contains($0.name ?? "") && structTypes[$0.type ?? ""] == nil
        }.compactMap(\.name))
        let bindings = try BufferBindings(
            parameters: parameterNodes, automaticResources: automaticResources,
            nonBindable: nonBindable, isEntryPoint: isEntryPoint
        )
        let parameters = try parameterNodes.map { parameter in
            try emitParameter(parameter, bufferSlot: bindings.slots[parameter.name ?? ""], isEntryPoint: isEntryPoint)
        }

        guard let body = node.firstChild(of: "brace_stmt") else {
            throw SchmetalError("function '\(name)' has no body")
        }
        let returnType = try metalReturnType(node["result"], context: "'\(name)'")

        let signature = """
        \(qualifier) \(returnType) \(name)(
            \(parameters.joined(separator: ",\n    "))
        )
        """
        if prototype {
            return signature + ";\n"
        }
        return signature + " " + (try emitBlock(body, indent: 0)) + "\n"
    }

    private func emitParameter(_ node: ASTNode, bufferSlot: Int?, isEntryPoint: Bool) throws -> String {
        guard let name = node.name else { throw SchmetalError("unnamed parameter") }
        guard let type = node.type else { throw SchmetalError("parameter '\(name)' has no type") }

        if let attribute = ShaderLanguage.indexTypes[type] {
            return isEntryPoint ? "uint \(name) [[\(attribute)]]" : "uint \(name)"
        }

        if let element = bufferElement(of: type) {
            let elementType = try metalType(element, context: "Buffer element")
            guard !isEntryPoint || bufferSlot != nil else { throw SchmetalError("missing buffer binding for '\(name)'") }
            let binding = bufferSlot.map { " [[buffer(\($0))]]" } ?? ""
            return "device \(elementType) *\(name)\(binding)"
        }

        if let structure = structTypes[type] {
            if let bufferSlot {
                return "constant \(structure) &\(name) [[buffer(\(bufferSlot))]]"
            }
            // Unannotated struct parameters on entry points are rasterizer inputs.
            return isEntryPoint ? "\(structure) \(name) [[stage_in]]" : "\(structure) \(name)"
        }

        let mapped = try metalType(type, context: "parameter '\(name)'")
        if isEntryPoint {
            guard let bufferSlot else { throw SchmetalError("missing buffer binding for '\(name)'") }
            return "constant \(mapped) &\(name) [[buffer(\(bufferSlot))]]"
        }
        return "\(mapped) \(name)"
    }

    // MARK: - Statements

    private func emitBlock(_ node: ASTNode, indent: Int) throws -> String {
        let pad = String(repeating: "    ", count: indent + 1)
        var lines: [String] = []
        for statement in node.children {
            guard let text = try emitStatement(statement, indent: indent + 1) else { continue }
            lines.append(pad + text)
        }
        return "{\n" + lines.joined(separator: "\n") + "\n" + String(repeating: "    ", count: indent) + "}"
    }

    /// Returns nil for nodes that carry no runtime effect, such as the var_decl
    /// that accompanies a local pattern_binding_decl.
    private func emitStatement(_ node: ASTNode, indent: Int) throws -> String? {
        switch node.kind {
        case "pattern_binding_decl":
            try shaderDeclarations.validateBinding(node)
            guard let entry = node.firstChild(of: "pattern_entry"),
                  let named = entry.firstDescendant(of: "pattern_named"),
                  let name = named.name else {
                throw SchmetalError("malformed local declaration")
            }
            let type = try metalType(named.type, context: "local '\(name)'")
            guard let initializer = entry.children.first(where: { $0["label"] == "processed_init" }) else {
                return "\(type) \(name);"
            }
            return "\(type) \(name) = \(try emitExpression(initializer));"

        case "typealias":
            return nil
        case "var_decl":
            try shaderDeclarations.validateProperty(node, allowWrapper: false)
            return nil

        case "assign_expr":
            guard node.children.count == 2 else { throw SchmetalError("malformed assignment") }
            return "\(try emitExpression(node.children[0])) = \(try emitExpression(node.children[1]));"

        case "return_stmt":
            guard let value = node.children.first else { return "return;" }
            return "return \(try emitExpression(value));"

        case "if_stmt":
            let parts = node.children
            guard parts.count >= 2 else { throw SchmetalError("malformed if") }
            var text = "if (\(try emitCondition(parts[0]))) \(try emitBlock(parts[1], indent: indent))"
            if parts.count >= 3 {
                let alternative = parts[2]
                text += alternative.kind == "brace_stmt"
                    ? " else \(try emitBlock(alternative, indent: indent))"
                    : " else \(try emitStatement(alternative, indent: indent) ?? ";")"
            }
            return text

        case "while_stmt":
            let parts = node.children
            guard parts.count == 2 else { throw SchmetalError("malformed while") }
            return "while (\(try emitCondition(parts[0]))) \(try emitBlock(parts[1], indent: indent))"

        case "brace_stmt":
            return try emitBlock(node, indent: indent)

        default:
            return "\(try emitExpression(node));"
        }
    }

    private func emitCondition(_ node: ASTNode) throws -> String {
        guard node.kind == "array", node["label"] == "conditions", !node.children.isEmpty,
              node.children.allSatisfy({ $0.type == "Swift.Bool" }) else {
            throw SchmetalError("only Boolean conditions are supported")
        }
        return try node.children.map { "(\(try emitExpression($0)))" }.joined(separator: " && ")
    }

}

extension Emitter {
    // MARK: - Expressions

    private func emitExpression(_ node: ASTNode) throws -> String {
        switch node.kind {
        case "integer_literal_expr":
            guard let value = node["value"] else { throw SchmetalError("integer literal without value") }
            return node["negative"] == "true" ? "-" + value : value

        case "float_literal_expr":
            guard let value = node["value"] else { throw SchmetalError("float literal without value") }
            return node["negative"] == "true" ? "-" + value : value

        case "boolean_literal_expr":
            return node["value"] ?? "false"

        case "declref_expr":
            guard let name = node.declBaseName else { throw SchmetalError("unresolved reference") }
            return name

        case "member_ref_expr":
            try shaderDeclarations.validateMember(node)
            guard let base = node.children.first else { throw SchmetalError("malformed member access") }
            guard let member = node.declBaseName else { throw SchmetalError("unresolved member") }
            // An index parameter is already a uint in Metal, so `.raw` is a no-op.
            if member == ShaderLanguage.indexRawComponent, ShaderLanguage.indexTypes[base.type ?? ""] != nil {
                return try emitExpression(base)
            }
            return "\(try emitExpression(base)).\(member)"

        case "subscript_expr":
            try shaderDeclarations.validateSubscript(node)
            guard let base = node.children.first,
                  let arguments = node.firstChild(of: "argument_list"),
                  let index = arguments.children(of: "argument").first?.children.first else {
                throw SchmetalError("malformed subscript")
            }
            return "\(try emitExpression(base))[\(try emitExpression(index))]"

        case "binary_expr":
            return try emitBinary(node)

        case "prefix_unary_expr":
            guard let callee = node.firstDescendant(of: "declref_expr"),
                  let operatorName = callee.declBaseName,
                  let operand = node.firstChild(of: "argument_list")?
                      .children(of: "argument").first?.children.first else {
                throw SchmetalError("malformed unary expression")
            }
            try shaderDeclarations.validateOperator(callee, name: operatorName)
            return "\(operatorName)\(try emitExpression(operand))"

        case "paren_expr":
            guard let inner = node.children.first else { return "()" }
            return "(\(try emitExpression(inner)))"

        case "ternary_expr":
            let parts = node.children
            guard parts.count == 3 else { throw SchmetalError("malformed ternary") }
            return "(\(try emitExpression(parts[0])) ? \(try emitExpression(parts[1])) : \(try emitExpression(parts[2])))"

        case "call_expr":
            return try emitCall(node)

        // swiftc inserts these around values; they have no MSL spelling.
        case "load_expr", "inout_expr", "paren_expr_implicit", "coerce_expr",
             "dot_syntax_call_expr", "abi_safe_conversion_expr":
            guard let inner = node.children.first else {
                throw SchmetalError("empty \(node.kind)")
            }
            return try emitExpression(inner)

        case "constructor_ref_call_expr", "type_expr":
            throw SchmetalError("unsupported type reference in expression position")

        default:
            throw SchmetalError("unsupported expression: \(node.kind)")
        }
    }

    /// `a * b` arrives as binary_expr(dot_syntax_call_expr(operator), argument_list).
    private func emitBinary(_ node: ASTNode) throws -> String {
        guard let callee = node.children.first,
              let reference = callee.firstDescendant(of: "declref_expr"),
              let operatorName = reference.declBaseName else {
            throw SchmetalError("unresolved operator")
        }
        try shaderDeclarations.validateOperator(reference, name: operatorName)
        guard let arguments = node.firstChild(of: "argument_list") else {
            throw SchmetalError("operator '\(operatorName)' has no arguments")
        }
        let argumentNodes = arguments.children(of: "argument").compactMap(\.children.first)
        let operands = try argumentNodes.enumerated().map { index, operand in
            if index == 1, ["&&", "||"].contains(operatorName), operand.kind == "autoclosure_expr" {
                guard operand.children.count == 2, operand.children[0].kind == "parameter_list",
                      operand.children[0].children.isEmpty, operand.children[1].type == "Swift.Bool" else {
                    throw SchmetalError("unsupported Boolean autoclosure")
                }
                return try emitExpression(operand.children[1])
            }
            return try emitExpression(operand)
        }
        guard operands.count == 2 else {
            throw SchmetalError("operator '\(operatorName)' expects two operands")
        }

        let mapped: String
        switch operatorName {
        case "&&": mapped = "&&"
        case "||": mapped = "||"
        case "+", "-", "*", "/", "%", "<", ">", "<=", ">=", "==", "!=",
             "&", "|", "^", "<<", ">>":
            mapped = operatorName
        default:
            throw SchmetalError("unsupported operator '\(operatorName)'")
        }
        return "(\(operands[0]) \(mapped) \(operands[1]))"
    }

    private func emitCall(_ node: ASTNode) throws -> String {
        guard let callee = node.children.first else { throw SchmetalError("malformed call") }
        guard let arguments = node.firstChild(of: "argument_list") else {
            throw SchmetalError("call has no argument list")
        }
        let operands = try arguments.children(of: "argument").compactMap(\.children.first).map { try emitExpression($0) }

        // A struct initializer reaches us as constructor_ref_call_expr whose
        // type_expr names the type; everything else is a plain function.
        if callee.kind == "constructor_ref_call_expr" {
            guard let typeName = callee.firstDescendant(of: "type_expr")?["typerepr"],
                  let reference = callee.firstDescendant(of: "declref_expr") else {
                throw SchmetalError("unresolved initializer")
            }
            try shaderDeclarations.validateConstructor(
                reference, typeName: typeName, shaderStruct: structTypes[typeName] != nil
            )
            if let mapped = ShaderLanguage.constructors[typeName] {
                return "\(mapped)(\(operands.joined(separator: ", ")))"
            }
            if let structure = structTypes[typeName] {
                return "\(structure) { \(operands.joined(separator: ", ")) }"
            }
            throw SchmetalError("no Metal constructor for '\(typeName)'")
        }

        guard callee.kind == "declref_expr", let signature = callee.declBaseName else {
            throw SchmetalError("only direct calls to supported declarations are allowed")
        }
        if let helper = try shaderDeclarations.helperName(for: callee) {
            return "\(helper)(\(operands.joined(separator: ", ")))"
        }
        let name = String(signature.prefix { $0 != "(" })
        let supported = shaderDeclarations.isPreludeFunction(callee, name: name)
            || shaderDeclarations.isSwiftIntrinsic(callee, name: name)
        if let intrinsic = ShaderLanguage.intrinsicsByName[name], supported {
            return "\(intrinsic.metal)(\(operands.joined(separator: ", ")))"
        }
        throw SchmetalError("unsupported function declaration: \(callee["decl"] ?? signature)")
    }

    // MARK: - Types

    /// `Buffer<Float4>` → `Float4`.
    private func bufferElement(of type: String) -> String? {
        let prefix = ShaderLanguage.bufferType + "<"
        guard type.hasPrefix(prefix), type.hasSuffix(">") else { return nil }
        return String(type.dropFirst(prefix.count).dropLast())
    }

    private func metalReturnType(_ type: String?, context: String) throws -> String {
        guard let type, type != "()" else { return "void" }
        return try metalType(type, context: context)
    }

    private func metalType(_ type: String?, context: String) throws -> String {
        guard let type else { throw SchmetalError("\(context) has no type") }

        if let structure = structTypes[type] { return structure }
        if let element = bufferElement(of: type) {
            return "device \(try metalType(element, context: context)) *"
        }
        guard let mapped = ShaderLanguage.metalTypes[type] else {
            throw SchmetalError("no Metal type for '\(type)' in \(context)")
        }
        return mapped
    }
}
